/*
  REFINED SUPABASE SQL SCHEMA FOR PRINCE AND PRINCESS INTERNATIONAL SCHOOL
  
  This version includes:
  - Drop statements for a clean start
  - Recursive policy fixes
  - Trigger improvements
*/

-- 0. CLEANUP (Optional: Uncomment if you want to start fresh)
-- DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
-- DROP FUNCTION IF EXISTS public.handle_new_user();
-- DROP TABLE IF EXISTS results;
-- DROP TABLE IF EXISTS teacher_classes;
-- DROP TABLE IF EXISTS teacher_subjects;
-- DROP TABLE IF EXISTS students;
-- DROP TABLE IF EXISTS class_subjects;
-- DROP TABLE IF EXISTS subjects;
-- DROP TABLE IF EXISTS classes;
-- DROP TABLE IF EXISTS settings;
-- DROP TABLE IF EXISTS profiles;
-- DROP TYPE IF EXISTS user_role;

-- Create user_role enum if it doesn't exist
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('admin', 'teacher', 'student', 'cashier');
    ELSE
        -- Ensure all roles exist in the enum
        ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'student';
        ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'teacher';
        ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'admin';
        ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'cashier';
        ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'exam_officer';
    END IF;
END $$;

-- Drop legacy check constraint on profiles if it exists
DO $$ BEGIN
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
EXCEPTION
    WHEN undefined_object THEN null;
END $$;

-- Ensure profiles table uses the enum and has correct default
ALTER TABLE public.profiles 
  ALTER COLUMN role TYPE user_role USING role::user_role,
  ALTER COLUMN role SET DEFAULT 'teacher'::user_role;

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT UNIQUE,
  email TEXT NOT NULL,
  role user_role DEFAULT 'teacher',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- 2. Classes Table
CREATE TABLE IF NOT EXISTS classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name TEXT NOT NULL UNIQUE,
  category TEXT DEFAULT 'Junior' CHECK (category IN ('Junior', 'Senior')),
  teacher_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE classes ENABLE ROW LEVEL SECURITY;

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;

-- 4. Class Subjects (Pivot)
CREATE TABLE IF NOT EXISTS class_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  UNIQUE(class_id, subject_id)
);

ALTER TABLE class_subjects ENABLE ROW LEVEL SECURITY;

-- 5. Students Table
CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  middle_name TEXT,
  gender TEXT CHECK (gender IN ('Male', 'Female', 'Other')),
  admission_number TEXT UNIQUE NOT NULL,
  class_id BIGINT REFERENCES classes(id) ON DELETE SET NULL,
  teacher_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  parent_name TEXT,
  parent_contact TEXT,
  address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Ensure the relationship exists for PostgREST
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'students_teacher_id_fkey'
    ) THEN
        ALTER TABLE students ADD CONSTRAINT students_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES profiles(id) ON DELETE SET NULL;
    END IF;
END $$;

ALTER TABLE students ENABLE ROW LEVEL SECURITY;

-- AUTOMATIC STUDENT USER CREATION & SYNC
-- This function creates/updates an auth user and profile for each student
CREATE OR REPLACE FUNCTION public.handle_student_changes()
RETURNS trigger AS $$
DECLARE
  new_user_id UUID;
BEGIN
  -- 1. Handle INSERT
  IF (TG_OP = 'INSERT') THEN
    -- Check if the user already exists to avoid errors
    SELECT id INTO new_user_id FROM auth.users WHERE email = (NEW.admission_number || '@school.com');
    
    IF new_user_id IS NULL THEN
      INSERT INTO auth.users (
        instance_id,
        id,
        aud,
        role,
        email,
        encrypted_password,
        email_confirmed_at,
        recovery_sent_at,
        last_sign_in_at,
        raw_app_meta_data,
        raw_user_meta_data,
        created_at,
        updated_at,
        confirmation_token,
        email_change,
        email_change_token_new,
        recovery_token
      )
      VALUES (
        '00000000-0000-0000-0000-000000000000',
        gen_random_uuid(),
        'authenticated',
        'authenticated',
        NEW.admission_number || '@school.com',
        crypt(NEW.admission_number, gen_salt('bf')), -- Admission number as password (always >= 6 chars)
        now(),
        now(),
        now(),
        '{"provider":"email","providers":["email"]}',
        jsonb_build_object('name', NEW.first_name || ' ' || NEW.last_name, 'role', 'student', 'username', NEW.admission_number),
        now(),
        now(),
        '',
        '',
        '',
        ''
      )
      RETURNING id INTO new_user_id;
    END IF;

    -- Create/Update Profile
    INSERT INTO public.profiles (id, name, username, email, role)
    VALUES (
      new_user_id,
      NEW.first_name || ' ' || NEW.last_name,
      NEW.admission_number,
      NEW.admission_number || '@school.com',
      'student'
    )
    ON CONFLICT (id) DO UPDATE SET
      username = EXCLUDED.username,
      name = EXCLUDED.name,
      email = EXCLUDED.email,
      role = 'student';

  -- 2. Handle UPDATE
  ELSIF (TG_OP = 'UPDATE') THEN
    -- If surname or admission number changed, update auth and profile
    IF (NEW.last_name <> OLD.last_name OR NEW.admission_number <> OLD.admission_number OR NEW.first_name <> OLD.first_name) THEN
      -- Update auth user
      UPDATE auth.users 
      SET encrypted_password = crypt(NEW.admission_number, gen_salt('bf')),
          email = NEW.admission_number || '@school.com',
          raw_user_meta_data = raw_user_meta_data || jsonb_build_object('name', NEW.first_name || ' ' || NEW.last_name, 'username', NEW.admission_number),
          updated_at = now()
      WHERE email = OLD.admission_number || '@school.com';
      
      -- Update profile
      UPDATE public.profiles
      SET name = NEW.first_name || ' ' || NEW.last_name,
          username = NEW.admission_number,
          email = NEW.admission_number || '@school.com'
      WHERE username = OLD.admission_number;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for student changes
DROP TRIGGER IF EXISTS on_student_changes ON students;
CREATE TRIGGER on_student_changes
  AFTER INSERT OR UPDATE ON students
  FOR EACH ROW EXECUTE PROCEDURE public.handle_student_changes();

-- BULK SYNC FUNCTION FOR EXISTING STUDENTS
CREATE OR REPLACE FUNCTION public.sync_all_students()
RETURNS text AS $$
DECLARE
  student_record RECORD;
  sync_count INTEGER := 0;
  new_user_id UUID;
BEGIN
  FOR student_record IN SELECT * FROM public.students LOOP
    -- Check if user already exists
    SELECT id INTO new_user_id FROM auth.users WHERE email = (student_record.admission_number || '@school.com');
    
    IF new_user_id IS NULL THEN
      INSERT INTO auth.users (
        instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
        raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token
      )
      VALUES (
        '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
        student_record.admission_number || '@school.com', crypt(student_record.admission_number, gen_salt('bf')),
        now(), '{"provider":"email","providers":["email"]}',
        jsonb_build_object('name', student_record.first_name || ' ' || student_record.last_name, 'role', 'student', 'username', student_record.admission_number),
        now(), now(), ''
      )
      RETURNING id INTO new_user_id;
      sync_count := sync_count + 1;
    END IF;

    -- Upsert profile
    INSERT INTO public.profiles (id, name, username, email, role)
    VALUES (
      new_user_id,
      student_record.first_name || ' ' || student_record.last_name,
      student_record.admission_number,
      student_record.admission_number || '@school.com',
      'student'
    )
    ON CONFLICT (id) DO UPDATE SET
      username = EXCLUDED.username,
      name = EXCLUDED.name,
      email = EXCLUDED.email,
      role = 'student';
  END LOOP;
  
  RETURN 'Synced ' || sync_count || ' students.';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Psychomotor Skills Table
CREATE TABLE IF NOT EXISTS psychomotor_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  -- Psychomotor
  handwriting INTEGER DEFAULT 0,
  fluency INTEGER DEFAULT 0,
  games INTEGER DEFAULT 0,
  sports INTEGER DEFAULT 0,
  gymnastics INTEGER DEFAULT 0,
  handling_tools INTEGER DEFAULT 0,
  drawing_painting INTEGER DEFAULT 0,
  crafts INTEGER DEFAULT 0,
  musical_skills INTEGER DEFAULT 0,
  -- Affective
  punctuality INTEGER DEFAULT 0,
  neatness INTEGER DEFAULT 0,
  politeness INTEGER DEFAULT 0,
  honesty INTEGER DEFAULT 0,
  relationship_with_others INTEGER DEFAULT 0,
  leadership INTEGER DEFAULT 0,
  emotional_stability INTEGER DEFAULT 0,
  health INTEGER DEFAULT 0,
  self_control INTEGER DEFAULT 0,
  attentiveness INTEGER DEFAULT 0,
  perseverance INTEGER DEFAULT 0,
  -- Attendance
  days_present INTEGER DEFAULT 0,
  days_absent INTEGER DEFAULT 0,
  total_days INTEGER DEFAULT 0,
  -- Remarks
  teacher_remark TEXT,
  principal_remark TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(student_id, term, session)
);

ALTER TABLE psychomotor_skills ENABLE ROW LEVEL SECURITY;

-- 6.1 Attendance Records Table (Daily)
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT CHECK (status IN ('Present', 'Absent')),
  remark TEXT,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(student_id, date)
);

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

-- Attendance
DROP POLICY IF EXISTS "Attendance is viewable by everyone" ON public.attendance;
DROP POLICY IF EXISTS "Teachers can insert attendance" ON public.attendance;
DROP POLICY IF EXISTS "Teachers can update attendance" ON public.attendance;
DROP POLICY IF EXISTS "Teachers can delete attendance" ON public.attendance;
DROP POLICY IF EXISTS "Admins can insert attendance" ON public.attendance;
DROP POLICY IF EXISTS "Admins can update attendance" ON public.attendance;
DROP POLICY IF EXISTS "Admins can delete attendance" ON public.attendance;

CREATE POLICY "Attendance is viewable by everyone" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "Staff can manage attendance" ON public.attendance 
  FOR ALL 
  USING (is_admin() OR is_teacher()) 
  WITH CHECK (is_admin() OR is_teacher());

-- 7. Teacher Subjects (Pivot)
CREATE TABLE IF NOT EXISTS teacher_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  UNIQUE(teacher_id, subject_id)
);

ALTER TABLE teacher_subjects ENABLE ROW LEVEL SECURITY;

-- 7. Teacher Classes (Pivot)
CREATE TABLE IF NOT EXISTS teacher_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  UNIQUE(teacher_id, class_id)
);

ALTER TABLE teacher_classes ENABLE ROW LEVEL SECURITY;

-- 8. Results Table
CREATE TABLE IF NOT EXISTS results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  ca1_score NUMERIC DEFAULT 0 CHECK (ca1_score <= 20),
  ca2_score NUMERIC DEFAULT 0 CHECK (ca2_score <= 20),
  exam_score NUMERIC DEFAULT 0 CHECK (exam_score <= 70),
  total_score NUMERIC GENERATED ALWAYS AS (ca1_score + ca2_score + exam_score) STORED,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(student_id, subject_id, term, session)
);

ALTER TABLE results ENABLE ROW LEVEL SECURITY;

-- 8.1 Fee Standards (Default fees per class)
CREATE TABLE IF NOT EXISTS fee_standards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(class_id, term, session)
);

ALTER TABLE fee_standards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Fee standards are viewable by all staff" ON fee_standards;
DROP POLICY IF EXISTS "Only admins can manage fee standards" ON fee_standards;
DROP POLICY IF EXISTS "Admins can insert fee standards" ON fee_standards;
DROP POLICY IF EXISTS "Admins can update fee standards" ON fee_standards;
DROP POLICY IF EXISTS "Admins can delete fee standards" ON fee_standards;

CREATE POLICY "Fee standards are viewable by all staff" ON fee_standards 
  FOR SELECT USING (is_admin() OR is_teacher() OR is_cashier());

CREATE POLICY "Admins can manage fee standards" ON fee_standards 
  FOR ALL USING (is_admin());

-- 8.2 Fee Records Table
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fee_payment_status') THEN
        CREATE TYPE fee_payment_status AS ENUM ('Paid', 'Partial', 'Not Paid');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS fee_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  total_amount NUMERIC DEFAULT 0,
  amount_paid NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Not Paid',
  results_locked BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(student_id, term, session)
);

-- Safely add missing columns or change types
DO $$ BEGIN
    -- Add last_updated_by if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='fee_records' AND column_name='last_updated_by') THEN
        ALTER TABLE fee_records ADD COLUMN last_updated_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
    END IF;

    -- Add updated_at if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='fee_records' AND column_name='updated_at') THEN
        ALTER TABLE fee_records ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    END IF;

    -- Convert status to enum if it's still text
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'fee_records' AND column_name = 'status' AND data_type = 'text'
    ) THEN
        ALTER TABLE fee_records ALTER COLUMN status DROP DEFAULT;
        ALTER TABLE fee_records ALTER COLUMN status TYPE fee_payment_status USING (
            CASE 
                WHEN status = 'Paid' THEN 'Paid'::fee_payment_status
                WHEN status = 'Partial' THEN 'Partial'::fee_payment_status
                ELSE 'Not Paid'::fee_payment_status
            END
        );
        ALTER TABLE fee_records ALTER COLUMN status SET DEFAULT 'Not Paid'::fee_payment_status;
    END IF;
END $$;

-- Compute balance column if it doesn't exist
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='fee_records' AND column_name='balance') THEN
        ALTER TABLE fee_records ADD COLUMN balance NUMERIC GENERATED ALWAYS AS (total_amount - amount_paid) STORED;
    END IF;
END $$;

-- 8.2 Fee Transactions Table
CREATE TABLE IF NOT EXISTS fee_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fee_record_id BIGINT REFERENCES fee_records(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  payment_method TEXT CHECK (payment_method IN ('Cash', 'Bank Transfer', 'POS', 'Online')),
  cashier_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  transaction_date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  receipt_number TEXT UNIQUE DEFAULT 'REC-' || upper(substring(gen_random_uuid()::text from 1 for 8))
);

ALTER TABLE fee_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE fee_transactions ENABLE ROW LEVEL SECURITY;

-- Policies for transactions
DROP POLICY IF EXISTS "Fee transactions viewable by admins and cashiers" ON fee_transactions;
DROP POLICY IF EXISTS "Cashiers can insert transactions" ON fee_transactions;
DROP POLICY IF EXISTS "Staff can manage transactions" ON fee_transactions;

CREATE POLICY "Fee transactions viewable by admins and cashiers" ON fee_transactions 
  FOR SELECT USING (is_admin() OR is_cashier());

CREATE POLICY "Staff can manage transactions" ON fee_transactions 
  FOR ALL USING (is_admin() OR is_cashier());

DROP POLICY IF EXISTS "Fee records are viewable by admins and cashiers" ON fee_records;
DROP POLICY IF EXISTS "Cashiers can manage fee records" ON fee_records;
DROP POLICY IF EXISTS "Admins can manage fee records" ON fee_records;
DROP POLICY IF EXISTS "Students can view their own fee status" ON fee_records;
DROP POLICY IF EXISTS "Cashiers can insert fee records" ON fee_records;
DROP POLICY IF EXISTS "Cashiers can update fee records" ON fee_records;
DROP POLICY IF EXISTS "Cashiers can delete fee records" ON fee_records;
DROP POLICY IF EXISTS "Admins can insert fee records" ON fee_records;
DROP POLICY IF EXISTS "Admins can update fee records" ON fee_records;
DROP POLICY IF EXISTS "Admins can delete fee records" ON fee_records;

CREATE POLICY "Fee records are viewable by admins and cashiers" ON fee_records 
  FOR SELECT USING (is_admin() OR is_cashier());

CREATE POLICY "Staff can manage fee records" ON fee_records 
  FOR ALL USING (is_admin() OR is_cashier());

CREATE POLICY "Students can view their own fee status" ON fee_records 
  FOR SELECT USING (student_id IN (SELECT id FROM students WHERE admission_number IN (SELECT username FROM profiles WHERE id = auth.uid())));

-- 10. Announcements Table
CREATE TABLE IF NOT EXISTS announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  target_role TEXT NOT NULL CHECK (target_role IN ('all', 'teacher', 'student')),
  target_class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'announcements' AND policyname = 'Announcements are viewable by everyone') THEN
        CREATE POLICY "Announcements are viewable by everyone" ON announcements FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'announcements' AND policyname = 'Admin can manage all announcements') THEN
        CREATE POLICY "Admin can manage all announcements" ON announcements FOR ALL USING (is_admin());
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'announcements' AND policyname = 'Teachers can manage their class announcements') THEN
        CREATE POLICY "Teachers can manage their class announcements" ON announcements FOR ALL USING (is_teacher() AND (target_role = 'student'));
    END IF;
END $$;

-- 11. Settings Table (Update)
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  school_name TEXT DEFAULT 'Prince and Princess International School',
  school_logo_url TEXT,
  school_motto TEXT,
  current_term TEXT DEFAULT '1st',
  current_session TEXT DEFAULT '2025/2026',
  next_term_begins TEXT,
  principal_signature_url TEXT,
  CONSTRAINT single_row CHECK (id = 1)
);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- INSERT DEFAULT SETTINGS
INSERT INTO settings (id, school_name, school_motto, current_term, current_session)
VALUES (1, 'Prince and Princess International School', 'Knowledge is Power', '1st', '2025/2026')
ON CONFLICT (id) DO UPDATE SET school_name = EXCLUDED.school_name;

-- TRIGGER FOR PROFILE CREATION
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public
AS $$
DECLARE
  default_role user_role := 'teacher';
  meta_role text;
BEGIN
  meta_role := new.raw_user_meta_data->>'role';
  
  INSERT INTO public.profiles (id, name, username, email, role)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'name', 'User'), 
    NULLIF(TRIM(new.raw_user_meta_data->>'username'), ''),
    new.email, 
    CASE 
      WHEN meta_role = 'admin' THEN 'admin'::user_role
      WHEN meta_role = 'teacher' THEN 'teacher'::user_role
      WHEN meta_role = 'student' THEN 'student'::user_role
      WHEN meta_role = 'cashier' THEN 'cashier'::user_role
      ELSE default_role
    END
  )
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    username = EXCLUDED.username,
    email = EXCLUDED.email,
    role = EXCLUDED.role;
    
  RETURN new;
EXCEPTION
  WHEN others THEN
    -- In a trigger, we should ideally not fail the main transaction
    -- But "Database error saving new user" often means the trigger failed and wasn't caught.
    -- We'll log it to the postgres log.
    RAISE WARNING 'Error in handle_new_user trigger for user %: %', new.id, SQLERRM;
    RETURN new;
END;
$$;

-- Drop trigger if exists before creating to avoid errors
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Function to sync role from profile to auth.users metadata
CREATE OR REPLACE FUNCTION public.sync_user_role_to_metadata()
RETURNS trigger AS $$
BEGIN
  UPDATE auth.users
  SET raw_user_meta_data = 
    COALESCE(raw_user_meta_data, '{}'::jsonb) || 
    jsonb_build_object('role', NEW.role::text)
  WHERE id = NEW.id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_profile_role_sync ON profiles;
CREATE TRIGGER on_profile_role_sync
  AFTER INSERT OR UPDATE OF role ON profiles
  FOR EACH ROW EXECUTE PROCEDURE public.sync_user_role_to_metadata();

-- 11. HELPER FUNCTIONS FOR RLS (Prevents recursion)
-- We use SECURITY DEFINER so they run as the owner (postgres) bypassing RLS
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
BEGIN
  -- 1. Check JWT metadata first (fastest)
  IF (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' THEN
    RETURN TRUE;
  END IF;

  -- 2. Fallback to profiles table
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'::public.user_role
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_teacher()
RETURNS boolean 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
BEGIN
  -- 1. Check JWT metadata
  IF (auth.jwt() -> 'user_metadata' ->> 'role') = 'teacher' THEN
    RETURN TRUE;
  END IF;

  -- 2. Fallback to profiles table
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'teacher'::public.user_role
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_cashier()
RETURNS boolean 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
BEGIN
  -- 1. Check JWT metadata
  IF (auth.jwt() -> 'user_metadata' ->> 'role') = 'cashier' THEN
    RETURN TRUE;
  END IF;

  -- 2. Fallback to profiles table
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'cashier'::public.user_role
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_exam_officer()
RETURNS boolean 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
BEGIN
  -- 1. Check JWT metadata
  IF (auth.jwt() -> 'user_metadata' ->> 'role') = 'exam_officer' THEN
    RETURN TRUE;
  END IF;

  -- 2. Fallback to profiles table
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'exam_officer'::public.user_role
  );
END;
$$;

-- Helper to check if user is any staff member (Admin or Teacher or Exam Officer)
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
BEGIN
  RETURN is_admin() OR is_teacher() OR is_exam_officer();
END;
$$;

-- 12. RLS POLICIES

-- Profiles
DROP POLICY IF EXISTS "Profiles are viewable by everyone" ON profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
DROP POLICY IF EXISTS "Admins can manage profiles" ON profiles;
DROP POLICY IF EXISTS "Admins can insert profiles" ON profiles;
DROP POLICY IF EXISTS "Admins can update profiles" ON profiles;
DROP POLICY IF EXISTS "Admins can delete profiles" ON profiles;

CREATE POLICY "Profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can manage profiles" ON profiles FOR ALL USING (is_admin() OR is_exam_officer());

-- Classes
DROP POLICY IF EXISTS "Classes are viewable by everyone" ON classes;
DROP POLICY IF EXISTS "Admins can manage classes" ON classes;
DROP POLICY IF EXISTS "Admins can insert classes" ON classes;
DROP POLICY IF EXISTS "Admins can update classes" ON classes;
DROP POLICY IF EXISTS "Admins can delete classes" ON classes;
CREATE POLICY "Classes are viewable by everyone" ON classes FOR SELECT USING (true);
CREATE POLICY "Admins can manage classes" ON classes FOR ALL USING (is_admin() OR is_exam_officer());

-- Subjects
DROP POLICY IF EXISTS "Subjects are viewable by everyone" ON subjects;
DROP POLICY IF EXISTS "Admins can manage subjects" ON subjects;
DROP POLICY IF EXISTS "Admins can insert subjects" ON subjects;
DROP POLICY IF EXISTS "Admins can update subjects" ON subjects;
DROP POLICY IF EXISTS "Admins can delete subjects" ON subjects;
CREATE POLICY "Subjects are viewable by everyone" ON subjects FOR SELECT USING (true);
CREATE POLICY "Admins can manage subjects" ON subjects FOR ALL USING (is_admin() OR is_exam_officer());

-- Students
DROP POLICY IF EXISTS "Students are viewable by everyone" ON students;
DROP POLICY IF EXISTS "Admins can manage students" ON students;
DROP POLICY IF EXISTS "Admins can insert students" ON students;
DROP POLICY IF EXISTS "Admins can update students" ON students;
DROP POLICY IF EXISTS "Admins can delete students" ON students;
CREATE POLICY "Students are viewable by everyone" ON students FOR SELECT USING (true);
CREATE POLICY "Admins can manage students" ON students FOR ALL USING (is_admin() OR is_exam_officer());

-- Results
DROP POLICY IF EXISTS "Results are viewable by everyone" ON results;
DROP POLICY IF EXISTS "Staff can manage results" ON results;
DROP POLICY IF EXISTS "Teachers can insert results" ON results;
DROP POLICY IF EXISTS "Teachers can update results" ON results;
DROP POLICY IF EXISTS "Teachers can delete results" ON results;
DROP POLICY IF EXISTS "Admins can insert results" ON results;
DROP POLICY IF EXISTS "Admins can update results" ON results;
DROP POLICY IF EXISTS "Admins can delete results" ON results;
CREATE POLICY "Results are viewable by everyone" ON results FOR SELECT USING (true);
CREATE POLICY "Staff can manage results" ON results FOR ALL USING (is_staff());

-- Psychomotor Skills
DROP POLICY IF EXISTS "Psychomotor are viewable by everyone" ON psychomotor_skills;
DROP POLICY IF EXISTS "Staff can manage psychomotor" ON psychomotor_skills;
DROP POLICY IF EXISTS "Teachers can insert psychomotor" ON psychomotor_skills;
DROP POLICY IF EXISTS "Teachers can update psychomotor" ON psychomotor_skills;
DROP POLICY IF EXISTS "Teachers can delete psychomotor" ON psychomotor_skills;
DROP POLICY IF EXISTS "Admins can insert psychomotor" ON psychomotor_skills;
DROP POLICY IF EXISTS "Admins can update psychomotor" ON psychomotor_skills;
DROP POLICY IF EXISTS "Admins can delete psychomotor" ON psychomotor_skills;
CREATE POLICY "Psychomotor are viewable by everyone" ON psychomotor_skills FOR SELECT USING (true);
CREATE POLICY "Staff can manage psychomotor" ON psychomotor_skills FOR ALL USING (is_staff());

-- Attendance
DROP POLICY IF EXISTS "Attendance is viewable by everyone" ON public.attendance;
DROP POLICY IF EXISTS "Staff can manage attendance" ON public.attendance;
DROP POLICY IF EXISTS "Teachers can insert attendance" ON public.attendance;
DROP POLICY IF EXISTS "Teachers can update attendance" ON public.attendance;
DROP POLICY IF EXISTS "Teachers can delete attendance" ON public.attendance;
DROP POLICY IF EXISTS "Admins can insert attendance" ON public.attendance;
DROP POLICY IF EXISTS "Admins can update attendance" ON public.attendance;
DROP POLICY IF EXISTS "Admins can delete attendance" ON public.attendance;
CREATE POLICY "Attendance is viewable by everyone" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "Staff can manage attendance" ON public.attendance FOR ALL USING (is_staff());

-- Class Subjects
DROP POLICY IF EXISTS "Class subjects are viewable by everyone" ON class_subjects;
DROP POLICY IF EXISTS "Admins can manage class subjects" ON class_subjects;
DROP POLICY IF EXISTS "Admins can insert class subjects" ON class_subjects;
DROP POLICY IF EXISTS "Admins can update class subjects" ON class_subjects;
DROP POLICY IF EXISTS "Admins can delete class subjects" ON class_subjects;
CREATE POLICY "Class subjects are viewable by everyone" ON class_subjects FOR SELECT USING (true);
CREATE POLICY "Admins can manage class subjects" ON class_subjects FOR ALL USING (is_admin() OR is_exam_officer());

-- Teacher Assignments
DROP POLICY IF EXISTS "Teacher assignments are viewable by everyone" ON teacher_classes;
DROP POLICY IF EXISTS "Admins can manage teacher assignments" ON teacher_classes;
DROP POLICY IF EXISTS "Admins can insert teacher assignments" ON teacher_classes;
DROP POLICY IF EXISTS "Admins can update teacher assignments" ON teacher_classes;
DROP POLICY IF EXISTS "Admins can delete teacher assignments" ON teacher_classes;
CREATE POLICY "Teacher assignments are viewable by everyone" ON teacher_classes FOR SELECT USING (true);
CREATE POLICY "Admins can manage teacher assignments" ON teacher_classes FOR ALL USING (is_admin() OR is_exam_officer());

-- Teacher Subjects (Pivot)
DROP POLICY IF EXISTS "Teacher subjects are viewable by everyone" ON teacher_subjects;
DROP POLICY IF EXISTS "Admins can manage teacher subjects" ON teacher_subjects;
DROP POLICY IF EXISTS "Admins can insert teacher subjects" ON teacher_subjects;
DROP POLICY IF EXISTS "Admins can update teacher subjects" ON teacher_subjects;
DROP POLICY IF EXISTS "Admins can delete teacher subjects" ON teacher_subjects;
CREATE POLICY "Teacher subjects are viewable by everyone" ON teacher_subjects FOR SELECT USING (true);
CREATE POLICY "Admins can manage teacher subjects" ON teacher_subjects FOR ALL USING (is_admin() OR is_exam_officer());

-- Settings
DROP POLICY IF EXISTS "Settings are viewable by everyone" ON settings;
DROP POLICY IF EXISTS "Admins can update settings" ON settings;
CREATE POLICY "Settings are viewable by everyone" ON settings FOR SELECT USING (true);
CREATE POLICY "Admins can manage settings" ON settings FOR ALL USING (is_admin());


-- STORAGE BUCKET
-- Note: Buckets are usually created via UI or API, but here is the policy logic
-- INSERT INTO storage.buckets (id, name, public) VALUES ('school-assets', 'school-assets', true);
